version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8.6"
    steps:
      - checkout
      - run: python3 main.py

  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8.6"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install pytest
      - run: python3 -m pytest

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

